name: CI/CD - build & deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # מומלץ: משתמשים באקשן הרישמי להתחברות לדוקר האב
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }} # לדוגמה: amikahlon
          password: ${{ secrets.DOCKER_TOKEN }} # ה-Token שיצרת בדוקר האב

      # אפשר לבנות עם docker/build-push-action או בפקודה רגילה. כאן פשוט.
      - name: Build image
        run: docker build . --tag amikahlon/trivia:latest

      - name: Push to Docker Hub
        run: docker push amikahlon/trivia:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy app over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }} # IP/דומיין של השרת
          username: ${{ secrets.USER }} # משתמש SSH (למשל ubuntu)
          key: ${{ secrets.PRIVATE_KEY }} # ה-PEM (Key Pair) כסוד
          port: ${{ secrets.PORT }} # בד"כ 22
          script_stop: true
          script: |
            set -e
            # מושכים את הגרסה החדשה מה-Docker Hub
            sudo docker pull amikahlon/trivia:latest

            # עוצרים/מוחקים קונטיינר ישן אם קיים
            sudo docker stop trivia || true
            sudo docker rm trivia || true

            # מריצים את הקונטיינר המעודכן
            sudo docker run --name trivia -d -p 80:3000 --restart=always amikahlon/trivia:latest

            # ניקוי אימג'ים ישנים
            sudo docker image prune -f
